[package]
name = "maivin-recorder"
description = "Maivin MCAP Recorder"
authors = ["Au-Zone Technologies"]
version = "0.1.0"
edition = "2021"

[lib]
name = "maivin_reader"

[dependencies]
mcap ="0.9.0"
anyhow = "1.0"
serde = "1.0"
serde_derive = "1.0"
camino = "1.1.6"
memmap = "0.7.0"
cdr = "0.2"
zenoh = "0.10.0-rc"
zenoh-ros-type = { git = "https://github.com/MaivinAI/zenoh-ros-type" }
serde-big-array = "0.5.1"
futures = "0.3.29"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
hostname = "0.3.1"
log = "0.4.20"
clap = { version = "4.1", features = ["derive"] }
async-std = {version = "1.12", features = ["attributes"] }
async-scoped = {version = "0.8.0", features = ["use-async-std"] }
flume = "0.11.0"
ctrlc = "3.4.0"
env_logger = "0.9"