[package]
name = "maivin-recorder"
description = "Maivin MCAP Recorder"
authors = ["Au-Zone Technologies"]
version = "0.0.0"
edition = "2021"

[lib]
name = "maivin_reader"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[dependencies]
mcap ="0.9.0"
anyhow = "1.0"
serde = "1.0"
serde_derive = "1.0"
camino = "1.1.6"
memmap = "0.7.0"
cdr = "0.2"
zenoh = "0.10.0-rc"
edgefirst-schemas = "1.1"
serde-big-array = "0.5.1"
futures = "0.3.29"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
hostname = "0.4.0"
log = "0.4.20"
clap = { version = "4.1", features = ["derive", "env"] }
async-std = {version = "1.12", features = ["attributes"] }
async-scoped = {version = "0.9.0", features = ["use-async-std"] }
flume = "0.11.0"
ctrlc = "3.4.0"
env_logger = "0.11.3"
bus = "2.4.1"

[build-dependencies]
include_walk = "0.3"
