[package]
name = "maivin-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcap ="0.9.0"
anyhow = "1.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.3.3"
camino = "1.1.6"
memmap = "0.7.0"
cdr = "0.2"
zenoh = "0.10.0-rc"
zenoh-ros-type = { git = "https://github.com/MaivinAI/zenoh-ros-type" }